### ISSUE TITLE
[PE-D][Tester A] Tag appears at the end of success messages of 'student' even though no tag was added

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F12-2/tp#199]
After inputing an add student command such as `student /name John Doe /gender male /contact 98065432 /email joh@example.com /address 311, Clementi Ave 2, #02-25 /subject Physics /classes 7A,7B /attendance 0 /nok Bob Doe /emergency 87654321`, although no tag was given, the success message shows a Tag at the end: 
![Screenshot 2024-11-08 at 4.22.55 PM.png](https://raw.githubusercontent.com/annabellekk/ped/main/files/a1cd29b9-7771-43d1-bcf8-5fcb8f8cc791.png)
In contrast, if an optional field such as address is missing, it shows [missing address]. 

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: annabellekk/ped#3

**Comment by AgentHagu** [comment]
Possibly considered as UI text enhancement if we update the message to say "no tags", meaning it's a feature flaw 😢 

![384578966-655f566b-9f60-459f-b8ae-b1dd8bef5d96](https://github.com/user-attachments/assets/cf73d43a-fa23-4432-a23a-857ebdd4965f)

**Comment by AgentHagu** [comment]
Possible feature flaw. Consider under planned enhancement, though not a big priority.
