### ISSUE TITLE
[PE-D][Tester A] Duplicate person criteria not mentioned

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F12-2/tp#203]
It was not mentioned in the UG nor in the error message what is considered a duplicate student. The error message could be more informative in helping the user figure out why the input is considered a duplicate. I had to test out a few inputs to finally figure out it was because I had the same phone number and email address in my input. 

![Screenshot 2024-11-08 at 4.33.54 PM.png](https://raw.githubusercontent.com/annabellekk/ped/main/files/2ceb34d4-b22c-44bf-bb46-610b796679e9.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: annabellekk/ped#6

**Comment by AgentHagu** [comment]
We can update UG to specify this duplicate Person criteria. Not sure about UI message since it's probably considered an "enhancement"
![384578966-655f566b-9f60-459f-b8ae-b1dd8bef5d96](https://github.com/user-attachments/assets/6eab7757-31bf-4154-9c88-6502a48f0578)
