### ISSUE TITLE
[PE-D][Tester D] Only Second Value is taken for Duplicated Parameters

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F12-2/tp#211]
![Screenshot 2024-11-08 at 3.42.30 PM.png](https://raw.githubusercontent.com/samuelthen/ped/main/files/9439ae8b-57eb-46ff-92d7-4f00a35b755b.png)

![Screenshot 2024-11-08 at 3.42.46 PM.png](https://raw.githubusercontent.com/samuelthen/ped/main/files/1b5a3b24-f15c-4b84-90a9-f35c546504f0.png)

Duplicated parameters are not checked.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: samuelthen/ped#4

**Comment by AgentHagu** [comment]
Not familiar with the parser for this, is this a code error? Or something we didn't check (so feature flaw)

**Comment by AgentHagu** [comment]
Will address in UG that latest parameter for singular fields will be taken (such as /name or /address but not /tag)

**Comment by amoschee** [comment]
After checking the code, the latest parameter behaviour only happens in add student command
