### ISSUE TITLE
[PE-D][Tester D] Tag Prefix is documented wrongly

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F12-2/tp#215]
![Screenshot 2024-11-08 at 4.28.58 PM.png](https://raw.githubusercontent.com/samuelthen/ped/main/files/4f074edb-81c8-413a-812f-473458252a7b.png)

![Screenshot 2024-11-08 at 4.20.04 PM.png](https://raw.githubusercontent.com/samuelthen/ped/main/files/fc3ed885-f37d-48fe-a878-6ea706b40274.png)

-------------
Labels: `severity.High` `type.DocumentationBug`
original: samuelthen/ped#7

**Comment by AgentHagu** [comment]
They didn't explain but essentially our UG says the prefix is `/tags` but it's actually `/tag`

**Comment by AgentHagu** [comment]
Note: Typo in tag message, grammatical mistake. Should be "Tag names ..."
![image](https://github.com/user-attachments/assets/e4d99a78-4ebf-4716-b78f-f9f847190fa9)
