### ISSUE TITLE
[PE-D][Tester D] Spelling error educe

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F12-2/tp#222]
![Screenshot 2024-11-08 at 5.03.28 PM.png](https://raw.githubusercontent.com/samuelthen/ped/main/files/b7ef4dc0-f02a-4f83-8e5b-81e4c2c172fc.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: samuelthen/ped#9

**Comment by AgentHagu** [comment]
Duplicate issue of #252
