### ISSUE TITLE
[PE-D][Tester D] User Guide not Alphabetically Sorted

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F12-2/tp#229]
I do not think this is a big big issue when it really bothers me when I try to search for a command! thanks!

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: samuelthen/ped#10

**Comment by AgentHagu** [comment]
I think instead of alphabetical, we can probably still re-order or categorise our UG commands more.

Also standardise the order of the commands, they are different for features and command summary
