### ISSUE TITLE
[PE-D][Tester A] Keyword for gender could be case insensitive

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F12-2/tp#230]
Currently, the gender field in `student` command is case sensitive, however, there is no need for that as MALE, male, Male etc can all be understood to be referring to the male gender, since only two genders are allowed. 

![telegram-cloud-photo-size-5-6156898712341823391-y.jpg](https://raw.githubusercontent.com/annabellekk/ped/main/files/85d30fab-a67a-4c9c-b2fe-14423f3fa752.jpg)

![Screenshot 2024-11-08 at 5.11.23 PM.png](https://raw.githubusercontent.com/annabellekk/ped/main/files/fb899b45-ba0a-457e-a3fd-0ca803f97a56.png)
![Screenshot 2024-11-08 at 5.12.08 PM.png](https://raw.githubusercontent.com/annabellekk/ped/main/files/a0ee01b1-7540-4989-8932-90f424d35e13.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: annabellekk/ped#13

**Comment by AgentHagu** [comment]
According to that screenshot, I think we're forced to put it as feature flaw? Might be able to ask on forums if its bug instead

**Comment by AgentHagu** [comment]
Based on that screenshot, we are locked into Feature Flaw so consider under Planned Enhancements
