### ISSUE TITLE
[PE-D][Tester D] Phone number validation too restrictive for international contacts

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F12-2/tp#232]
Current implementation only accepts 8-digit phone numbers, making it impossible to add international students or teachers with different phone number formats. This limitation prevents the system from being used in schools with international students or staff.

What if their NOK is from other countries?

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: samuelthen/ped#12

**Comment by AgentHagu** [comment]
Feature flaw, consider under Planned Enhancements to loosen restrictions on phone number length or requirements to accomodate international phone numbers
