### ISSUE TITLE
[PE-D][Tester C] Editing a `Teacher`'s emergency contact changes his phone number

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F12-2/tp#233]
<i><video controls><source src="https://raw.githubusercontent.com/limyixiang/ped/main/files/4bbbf6af-2e9a-45a6-bc04-630d97bf0335.mp4" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/limyixiang/ped/main/files/4bbbf6af-2e9a-45a6-bc04-630d97bf0335.mp4</i>

As shown in the above video, editing a `Teacher`'s emergency contact changes his phone number, which should not be the case. The `Teacher`'s contact number should only be able to be edited using the `/contact` field, not the `/emergency` field. 

Do make sure to fix this bug to ensure that the user does not accidentally change a `Teacher`'s contact number!

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: limyixiang/ped#7

**Comment by AgentHagu** [comment]
Issue lies in this bit of code in `EditCommandParser.java`
![image](https://github.com/user-attachments/assets/f1b8d0b5-b211-4ba5-b6ea-7da2df8f7c69)

**Comment by AgentHagu** [comment]
Can fix the emergency changing the phone (incorrect behavior) but cannot prevent users from editing teacher's NOK or emergency (feature flaw). Consider that under Planned Enhancement
