### ISSUE TITLE
[PE-D][Tester D] Sort command fails to work with filtered list

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F12-2/tp#235]
Sort command doesn't maintain the current filter, making it impossible to sort a filtered subset of contacts. This forces users to reapply filters after sorting, reducing efficiency.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: samuelthen/ped#13

**Comment by AgentHagu** [comment]
Duplicate issue of #268
