### ISSUE TITLE
[PE-D][Tester D] Inaccurate Error Message

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F12-2/tp#238]
![Screenshot 2024-11-08 at 5.18.48 PM.png](https://raw.githubusercontent.com/samuelthen/ped/main/files/9e5a339e-8e80-4710-8084-673469f1499f.png)

Sam was a student previously, but the error message shows teacher

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: samuelthen/ped#16

**Comment by AgentHagu** [comment]
Duplicate issue of #258
