### ISSUE TITLE
[PE-D][Tester C] Missing spacing in `edit` command message prompt for parameters

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F12-2/tp#244]
![image.png](https://raw.githubusercontent.com/limyixiang/ped/main/files/9deb7b9f-1731-440d-a4e6-fd77fca53678.png)

In the above image, there seems to be missing spaces in the `Parameters:` section of the message prompt of the `edit` command.

This is possibly due to missing ` ` spacings when concatenating strings in your code. Do make sure to check that!

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: limyixiang/ped#8

**Comment by AgentHagu** [comment]
Not sure how strict they are with the definition of "enhancement" for text.
![image](https://github.com/user-attachments/assets/655f566b-9f60-459f-b8ae-b1dd8bef5d96)
