### ISSUE TITLE
MVP: Add Student Test Cases

### ISSUE THREAD

**Issue by nihalramesh12629** [AY2425S1-CS2103T-F12-2/tp#49]

**Comment by DanielVsh** [comment]
Hi @nihalramesh12629, can i contribute there?

**Comment by nihalramesh12629** [comment]
@DanielVsh who r u

**Comment by DanielVsh** [comment]
> @DanielVsh who r u

I am an uni student and i need to contribute some github issue, if you dont mind i could take it

**Comment by nihalramesh12629** [comment]
@DanielVsh nope
